mecanum_cmd_vel_to_voltage:
  ros__parameters:
    wheel_radius: 0.08
    half_wheelbase: 0.20  # L_x
    half_track: 0.18      # L_y
    kv: 0.02
    vmax: 24.0
    fl_sign: 1.0
    fr_sign: 1.0
    rl_sign: 1.0
    rr_sign: 1.0
    fl_topic: "/mecanum/front_left/voltage"
    fr_topic: "/mecanum/front_right/voltage"
    rl_topic: "/mecanum/rear_left/voltage"
    rr_topic: "/mecanum/rear_right/voltage"